-- =========================================
-- AMR FLEET DATABASE SCHEMA
-- =========================================

CREATE TABLE robots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL DEFAULT 0,
    y DOUBLE PRECISION NOT NULL DEFAULT 0,
    velocity DOUBLE PRECISION DEFAULT 0,
    battery DOUBLE PRECISION DEFAULT 100,
    status TEXT DEFAULT 'IDLE',
    current_task TEXT,
    priority INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- TASKS
-- =========================================

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL,
    pickup_x DOUBLE PRECISION,
    pickup_y DOUBLE PRECISION,
    destination_x DOUBLE PRECISION,
    destination_y DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    robot_id BIGINT REFERENCES robots(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- ROBOT-TO-ROBOT MESSAGES
-- =========================================

CREATE TABLE robot_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,
    receiver_id TEXT NOT NULL,
    message_type TEXT NOT NULL,
    position_x DOUBLE PRECISION,
    position_y DOUBLE PRECISION,
    velocity DOUBLE PRECISION,
    intent TEXT,
    priority INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- COLLISION EVENTS
-- =========================================

CREATE TABLE collision_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot1_id TEXT NOT NULL,
    robot2_id TEXT NOT NULL,
    distance DOUBLE PRECISION,
    action TEXT,
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
