-- =============================================================================
-- AMR FLEET DATABASE SCHEMA (PostgreSQL / Supabase Compatible)
-- Problem Statement SIH26123 - Bharat Electronics Limited (BEL)
-- =============================================================================

-- 1. ROBOTS TABLE
CREATE TABLE IF NOT EXISTS robots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL DEFAULT 0,
    y DOUBLE PRECISION NOT NULL DEFAULT 0,
    velocity DOUBLE PRECISION DEFAULT 0,
    battery DOUBLE PRECISION DEFAULT 100,
    status TEXT DEFAULT 'IDLE',
    current_task TEXT,
    priority INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TASKS TABLE
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL,
    pickup_x DOUBLE PRECISION,
    pickup_y DOUBLE PRECISION,
    destination_x DOUBLE PRECISION,
    destination_y DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    robot_id BIGINT REFERENCES robots(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ROBOT-TO-ROBOT MESSAGES (P2P Mesh / Supabase Ingress)
CREATE TABLE IF NOT EXISTS robot_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,
    receiver_id TEXT NOT NULL,
    message_type TEXT NOT NULL,
    position_x DOUBLE PRECISION,
    position_y DOUBLE PRECISION,
    velocity DOUBLE PRECISION,
    intent TEXT,
    priority INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. COLLISION EVENTS (Trajectory Conflict Resolution)
CREATE TABLE IF NOT EXISTS collision_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot1_id TEXT NOT NULL,
    robot2_id TEXT NOT NULL,
    distance DOUBLE PRECISION,
    action TEXT,
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- OPTIMIZED INDEXES FOR HIGH-THROUGHPUT AMR FLEET TELEMETRY
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_robots_robot_id ON robots(robot_id);
CREATE INDEX IF NOT EXISTS idx_robots_status ON robots(status);
CREATE INDEX IF NOT EXISTS idx_tasks_task_id ON tasks(task_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_robot_messages_receiver ON robot_messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_robot_messages_type ON robot_messages(message_type);
CREATE INDEX IF NOT EXISTS idx_collision_events_unresolved ON collision_events(resolved) WHERE resolved = FALSE;

-- =============================================================================
-- SEED DATA
-- =============================================================================

INSERT INTO robots (robot_id, name, x, y, velocity, battery, status, current_task, priority)
VALUES
('AMR_01', 'Warehouse Robot 1', 2.5, 4.0, 1.5, 92.0, 'IDLE', 'PICKUP_01', 1),
('AMR_02', 'Warehouse Robot 2', 8.0, 4.5, 1.2, 78.0, 'MOVING', 'DELIVERY_01', 2),
('AMR_03', 'Warehouse Robot 3', 5.0, 9.0, 1.0, 64.0, 'MOVING', 'PICKUP_02', 1)
ON CONFLICT (robot_id) DO NOTHING;

INSERT INTO tasks (task_id, type, pickup_x, pickup_y, destination_x, destination_y, status, robot_id)
VALUES
('TASK_001', 'PICKUP', 2.0, 4.0, 10.0, 8.0, 'ASSIGNED', (SELECT id FROM robots WHERE robot_id = 'AMR_01')),
('TASK_002', 'DELIVERY', 8.0, 4.0, 3.0, 10.0, 'IN_PROGRESS', (SELECT id FROM robots WHERE robot_id = 'AMR_02')),
('TASK_003', 'PICKUP', 5.0, 9.0, 12.0, 3.0, 'ASSIGNED', (SELECT id FROM robots WHERE robot_id = 'AMR_03'))
ON CONFLICT (task_id) DO NOTHING;

INSERT INTO robot_messages (sender_id, receiver_id, message_type, position_x, position_y, velocity, intent, priority)
VALUES
('AMR_01', 'AMR_02', 'POSITION_UPDATE', 2.5, 4.0, 1.5, 'MOVE_FORWARD', 1),
('AMR_02', 'AMR_01', 'INTENT_UPDATE', 8.0, 4.5, 1.2, 'TURN_RIGHT', 2),
('PATH_PLANNER', 'AMR_01', 'PATH_UPDATE', 2.5, 4.0, 0.0, 'PROCEED', 1);

INSERT INTO collision_events (robot1_id, robot2_id, distance, action, resolved)
VALUES
('AMR_01', 'AMR_02', 1.7, 'AMR_01_WAIT', TRUE);
